version: 0.2

phases:
   install:
   runtime-versions:
       java: openjdk8
    commands:
        - apt-get update -y
        - apt-get install -y maven
   build:
      - echo Entered the build phase....
      - mvn clean install
   post_build:
      commands:
       - echo Build completed successfully
artificats:
  files:
     - target/payment-service.jar
  discard-paths: yes
